export const SEARCH_CHANGE = "SEARCH_CHANGE";

export const FETCH_ROBOTS_START = "FETCH_ROBOTS_START";
export const FETCH_ROBOTS_SUCCESS = "FETCH_ROBOTS_SUCCESS";
export const FETCH_ROBOTS_FAIL = "FETCH_ROBOTS_FAIL";

export const ADD_ROBOT = "ADD_ROBOT";
